# Base configs
baseurl: ""
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Galéria | Kelemen Ákos"
subtitle: "Lásd a világot az én szememmel!"
author: "Kelemen Ákos"
header:
 title: "Kelemen Ákos"
 subtitle: "Készítette"
footer:
 name: "Üdvözöllek,"
 bio: "Ha megtetszett a munkám és szeretnél velem együtt dolgozni, nyugodtan írj rám Instagramon vagy töltsd ki az alábbi űrlapot!"
 github: "Igény esetén számlát is tudok kiállítani."
web_design: "KÁ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/AkosKele27"
  github: "https://www.github.com/Akos31"
